{% set name = "so4gp" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/so4gp-{{ version }}.tar.gz
  sha256: 27b0f55a60811e01ab0f9b24a3711d1ade206414a7c4b9792b43822f32673173

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.13
    - setuptools >=68.0
    - pip
  run:
    - python >=3.13
    - numpy >=2.2.4,<2.3.dev0
    - pandas >=2.2.3,<2.3.dev0
    - scikit-fuzzy >=0.5.0,<0.6.dev0
    - scikit-learn >=1.6.1,<1.7.dev0
    - python-dateutil >=2.9.0.post0,<2.10.dev0
    - tabulate >=0.9.0,<0.10.dev0
    - ypstruct
    - seaborn ==0.13.2

test:
  imports:
    - so4gp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Some Python optimization algorithms for mining gradual patterns.
  home: https://github.com/owuordickson/sogp_pypi
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owuordickson
