{% set name = "so4gp" %}
{% set version = "0.7.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/so4gp-{{ version }}.tar.gz
  sha256: 8966748c5c7d72697a46166a87664e2fec61596652dbe3044aa92f08097205e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.9
    - pip
  run:
    - python {{ python_min }}
    - numpy >=2.3.2,<2.4.dev0
    - pandas >=2.3.1,<2.4.dev0
    - scikit-fuzzy >=0.5.0,<0.6.dev0
    - scikit-learn >=1.7.1,<1.8.dev0
    - python-dateutil >=2.9.0.post0,<2.10.dev0
    - tabulate >=0.9.0,<0.10.dev0
    - seaborn >=0.13.2,<0.14.dev0

test:
  imports:
    - so4gp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Some Python optimization algorithms for mining gradual patterns.
  home: https://github.com/owuordickson/sogp_pypi
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owuordickson
