defaults:
  - _self_
  - method: tgraank
  - data_preprocess: default_preprocessing


#label_path: "datasets/1_random_3/east.p"
#label_path: "datasets/1_random_5/east.p"
#label_path: "datasets/close_3/east.p"
#label_path: "datasets/close_5/east.p"
#label_path: "datasets/confounder_3/east.p"
#label_path: "datasets/confounder_5/east.p"
#label_path: "datasets/random_3/east.p"
#label_path: "datasets/random_5/east.p"
label_path: "datasets/root_cause_3/east.p"
#label_path: "datasets/root_cause_5/east.p"
data_path: "product/rivers_ts_east_germany.csv"
save_path: "results/"
save_full_out: True


remove_diagonal: True
restrict_to: -1
dt_preprocess: True
